"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

import type { AdminProduct } from "@/lib/admin-products";
import { formatCurrency } from "@/lib/format";

export default function AdminProductDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const [product, setProduct] = useState<AdminProduct | null>(null); const [error, setError] = useState(false);
  useEffect(() => { void params.then(async ({ id }) => { try { const response = await fetch(`/api/admin/products/${id}`, { cache: "no-store" }); const payload = (await response.json()) as { ok: boolean; data?: AdminProduct }; if (!response.ok || !payload.ok || !payload.data) { setError(true); return; } setProduct(payload.data); } catch { setError(true); } }); }, [params]);
  if (error) return <State title="No pudimos encontrar este producto." />; if (!product) return <State title="Cargando producto..." />;
  return <div className="admin-workspace space-y-5"><Link className="text-sm font-semibold text-stone-600 underline underline-offset-4" href="/admin/productos">Productos</Link><section className="admin-panel px-5 py-6 sm:px-6"><p className="section-label">PRODUCTO</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold tracking-[-0.06em] text-stone-950">{product.name}</h1><p className="mt-2 text-sm text-stone-600">{product.brand} · {product.category} · {product.sku}</p></div><span className="rounded-full border border-stone-200 bg-white px-3 py-1.5 text-sm text-stone-700">{product.isActive ? "Activo" : "Borrador"}</span></div></section><div className="grid gap-5 xl:grid-cols-[0.8fr_1.2fr]"><section className="admin-panel px-5 py-6"><p className="section-label">INVENTARIO</p><p className="mt-3 text-3xl font-semibold tracking-[-0.06em] text-stone-950">{product.stock}</p><p className="mt-1 text-sm text-stone-600">unidades disponibles</p><p className="mt-6 text-sm text-stone-600">Precio</p><p className="mt-1 text-2xl font-semibold text-stone-950">{formatCurrency(product.price)}</p></section><section className="admin-panel px-5 py-6"><div className="flex items-end justify-between gap-4"><div><p className="section-label">MEDIA</p><h2 className="mt-2 text-2xl font-semibold tracking-[-0.05em] text-stone-950">Imagenes del producto</h2></div><Link className="text-sm font-semibold underline underline-offset-4" href={`/admin/productos?producto=${product.id}`}>Gestionar imagenes</Link></div>{product.imageObjects.length === 0 ? <p className="mt-5 text-sm text-stone-600">Aun no hay imagenes. Usa el panel de productos para subir la primera.</p> : <div className="mt-5 grid gap-3 sm:grid-cols-2">{product.imageObjects.map((image, index) => <a className="rounded-[1.2rem] border border-stone-200 bg-white p-4 text-sm text-stone-700" href={image.url} key={image.id} rel="noreferrer" target="_blank"><p className="font-semibold text-stone-950">Imagen {index + 1}{image.isPrimary ? " · Principal" : ""}</p><p className="mt-2 truncate text-stone-500">{image.altText ?? "Sin texto alternativo"}</p></a>)}</div>}</section></div></div>;
}
function State({ title }: { title: string }) { return <div className="admin-panel px-6 py-8"><p className="text-lg font-semibold text-stone-950">{title}</p><Link className="mt-4 inline-block text-sm font-semibold underline underline-offset-4" href="/admin/productos">Volver a productos</Link></div>; }
