"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

import { getAdminOrderStatusLabel, getAdminPaymentProviderLabel, getAdminPaymentStatusLabel, type AdminOrderDetail } from "@/lib/admin-orders";
import { formatCurrency, formatDateTime } from "@/lib/format";

export default function AdminOrderDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const [order, setOrder] = useState<AdminOrderDetail | null>(null);
  const [error, setError] = useState(false);
  useEffect(() => { void params.then(async ({ id }) => { try { const response = await fetch(`/api/admin/orders/${id}`, { cache: "no-store" }); const payload = (await response.json()) as { ok: boolean; data?: AdminOrderDetail }; if (!response.ok || !payload.ok || !payload.data) { setError(true); return; } setOrder(payload.data); } catch { setError(true); } }); }, [params]);
  if (error) return <DetailState title="No pudimos encontrar este pedido." href="/admin/pedidos" label="Volver a pedidos" />;
  if (!order) return <DetailState title="Cargando pedido..." href="/admin/pedidos" label="Volver" />;
  return <div className="admin-workspace space-y-5"><Link className="text-sm font-semibold text-stone-600 underline underline-offset-4" href="/admin/pedidos">Pedidos</Link><section className="admin-panel px-5 py-6 sm:px-6"><p className="section-label">PEDIDO</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold tracking-[-0.06em] text-stone-950">{order.orderNumber}</h1><p className="mt-2 text-sm text-stone-600">{formatDateTime(order.timestamps.createdAt)}</p></div><p className="text-2xl font-semibold text-stone-950">{formatCurrency(order.total)}</p></div><div className="mt-5 flex flex-wrap gap-2"><Pill label={getAdminOrderStatusLabel(order.status)} /><Pill label={getAdminPaymentStatusLabel(order.paymentStatus)} /><Pill label={getAdminPaymentProviderLabel(order.paymentProvider)} /></div></section><div className="grid gap-5 xl:grid-cols-[1.2fr_0.8fr]"><section className="admin-panel px-5 py-6"><p className="section-label">PRODUCTOS</p><div className="mt-4 divide-y divide-stone-100">{order.items.map((item) => <div className="flex justify-between gap-4 py-4" key={`${item.productId}-${item.productName}`}><div><p className="font-semibold text-stone-950">{item.productName}</p><p className="mt-1 text-sm text-stone-500">SKU / Producto #{item.productId} · Cantidad {item.quantity}</p></div><p className="font-semibold text-stone-900">{formatCurrency(item.unitPrice * item.quantity)}</p></div>)}</div><div className="mt-4 border-t border-stone-200 pt-4 text-sm text-stone-600"><p>Subtotal <span className="float-right text-stone-950">{formatCurrency(order.subtotal)}</span></p><p className="mt-2">Envio <span className="float-right text-stone-950">{formatCurrency(order.shippingTotal)}</span></p></div></section><div className="space-y-5"><InfoCard title="Cliente"><p className="font-semibold text-stone-950">{order.customer.name}</p><p className="mt-1 text-sm text-stone-600">{order.customer.email ?? "Sin email"}</p><p className="mt-1 text-sm text-stone-600">{order.customer.phone ?? "Sin telefono"}</p><Link className="mt-4 inline-block text-sm font-semibold underline underline-offset-4" href={`/admin/clientes/${order.customer.id}`}>Ver cliente</Link></InfoCard><InfoCard title="Envio"><p className="text-sm leading-6 text-stone-700">{order.shippingAddress.fullAddress}</p><p className="mt-3 text-sm text-stone-600">{order.shippingCarrier ?? "Sin paqueteria"}{order.trackingNumber ? ` · ${order.trackingNumber}` : ""}</p></InfoCard><InfoCard title="Pago"><p className="text-sm text-stone-700">{getAdminPaymentProviderLabel(order.paymentProvider)} · {getAdminPaymentStatusLabel(order.paymentStatus)}</p><p className="mt-2 text-sm text-stone-600">Referencia: {order.rawProviderReference ?? "Sin referencia"}</p></InfoCard></div></div></div>;
}

function DetailState({ title, href, label }: { title: string; href: string; label: string }) { return <div className="admin-panel px-6 py-8"><p className="text-lg font-semibold text-stone-950">{title}</p><Link className="mt-4 inline-block text-sm font-semibold underline underline-offset-4" href={href}>{label}</Link></div>; }
function Pill({ label }: { label: string }) { return <span className="rounded-full border border-stone-200 bg-white px-3 py-1.5 text-sm text-stone-700">{label}</span>; }
function InfoCard({ title, children }: { title: string; children: React.ReactNode }) { return <section className="admin-panel px-5 py-5"><p className="section-label">{title}</p><div className="mt-3">{children}</div></section>; }
