"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

import type { AdminCustomerDetail } from "@/lib/admin-customers";
import { formatCurrency, formatDateTime } from "@/lib/format";

export default function AdminCustomerDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const [customer, setCustomer] = useState<AdminCustomerDetail | null>(null); const [error, setError] = useState(false);
  useEffect(() => { void params.then(async ({ id }) => { try { const response = await fetch(`/api/admin/customers/${id}`, { cache: "no-store" }); const payload = (await response.json()) as { ok: boolean; data?: AdminCustomerDetail }; if (!response.ok || !payload.ok || !payload.data) { setError(true); return; } setCustomer(payload.data); } catch { setError(true); } }); }, [params]);
  const averageTicket = useMemo(() => customer && customer.ordersCount ? customer.totalSpent / customer.ordersCount : 0, [customer]);
  if (error) return <State title="No pudimos encontrar este cliente." />; if (!customer) return <State title="Cargando cliente..." />;
  return <div className="admin-workspace space-y-5"><Link className="text-sm font-semibold text-stone-600 underline underline-offset-4" href="/admin/clientes">Clientes</Link><section className="admin-panel px-5 py-6 sm:px-6"><p className="section-label">CLIENTE</p><h1 className="mt-3 text-3xl font-semibold tracking-[-0.06em] text-stone-950">{customer.name}</h1><p className="mt-2 text-sm text-stone-600">{customer.email ?? "Sin email"} · {customer.whatsapp ?? "Sin telefono"}</p><p className="mt-2 text-sm text-stone-500">Cliente desde {customer.createdAt ? formatDateTime(customer.createdAt) : "sin fecha"}</p><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Pedidos" value={String(customer.ordersCount)} /><Metric label="Importe gastado" value={formatCurrency(customer.totalSpent)} /><Metric label="Ticket promedio" value={formatCurrency(averageTicket)} /><Metric label="Ultima compra" value={customer.lastPurchaseAt ? formatDateTime(customer.lastPurchaseAt) : "Sin compras"} /></div></section><div className="grid gap-5 xl:grid-cols-[1.2fr_0.8fr]"><section className="admin-panel px-5 py-6"><p className="section-label">PEDIDOS</p>{customer.recentOrders.length === 0 ? <p className="mt-4 text-sm text-stone-600">Aun no hay pedidos asociados.</p> : <div className="mt-4 divide-y divide-stone-100">{customer.recentOrders.map((order) => <Link className="flex items-center justify-between gap-4 py-4" href={`/admin/pedidos/${order.id}`} key={order.id}><div><p className="font-semibold text-stone-950">{order.orderNumber}</p><p className="mt-1 text-sm text-stone-500">{formatDateTime(order.createdAt)} · {order.status}</p></div><p className="font-semibold text-stone-950">{formatCurrency(order.total)}</p></Link>)}</div>}</section><div className="space-y-5"><section className="admin-panel px-5 py-5"><p className="section-label">PERFIL DE PIEL</p><p className="mt-3 text-sm text-stone-700">{customer.skinType ? `Tipo de piel: ${customer.skinType}` : "Sin diagnostico asociado"}</p><p className="mt-2 text-sm text-stone-600">{customer.mainGoal ? `Objetivo: ${customer.mainGoal}` : "Completa un quiz para asociar objetivos y sensibilidad."}</p></section><section className="admin-panel px-5 py-5"><p className="section-label">ACTIVIDAD</p><p className="mt-3 text-sm text-stone-600">{customer.acceptedMarketing ? "Suscrito a novedades" : "No suscrito a novedades"}</p><p className="mt-2 text-sm text-stone-600">{customer.notes.length > 0 ? `${customer.notes.length} nota(s) disponible(s).` : "Sin actividad adicional registrada."}</p></section></div></div></div>;
}
function State({ title }: { title: string }) { return <div className="admin-panel px-6 py-8"><p className="text-lg font-semibold text-stone-950">{title}</p><Link className="mt-4 inline-block text-sm font-semibold underline underline-offset-4" href="/admin/clientes">Volver a clientes</Link></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-[1.2rem] border border-stone-200 bg-white px-4 py-4"><p className="text-sm text-stone-500">{label}</p><p className="mt-2 text-lg font-semibold text-stone-950">{value}</p></div>; }
